title: Мой сайт
description: Описание моего сайта
baseurl: "" # Основной URL (например, /blog)
url: "https://wpadmin.github.io" # URL вашего сайта

# Настройка меню
menu:
  - title: "Главная"
    url: "/"
  - title: "О нас"
    url: "/about"
  - title: "Услуги"
    url: "/services"
    submenu:
      - title: "Консалтинг"
        url: "/services/consulting"
      - title: "Разработка"
        url: "/services/development"
      - title: "Поддержка"
        url: "/services/support"
  - title: "Контакты"
    url: "/contact"